export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  APPRENANT = 'ROLE_APPRENANT',
  PARENT = 'ROLE_PARENT',
  PROFESSEUR = 'ROLE_PROFESSEUR',
  PROVISEUR = 'ROLE_PROVISEUR',
  DIRECTEUR = 'ROLE_DIRECTEUR',
  INSPECTEUR = 'ROLE_INSPECTEUR',
  SURVEILLANT = 'ROLE_SURVEILLANT',
  MEFPAI = 'ROLE_MEFPAI',
}
